name: ❓ Question
description: Something is unclear but not necessarily a bug
title: "[Question] "
labels: ["type:question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: What have you already tried or read?
    validations:
      required: true
